### ISSUE TITLE
Allow accessing ReceiveSbFile progress programatically

### ISSUE THREAD

**Issue by oplik0** [lpc55/lpc55-host#30]
Currently the implementation of ReceiveSbFile displays a progress bar in the terminal if the right feature is enabled (see https://github.com/lpc55/lpc55-host/blob/main/src/bootloader/protocol.rs#L263-L264), however it's currently impossible for non-cli applications to display the upload progress in a sensible manner.

Probably the most universal way of implementing that would be to allow passing a callback that'd be called every chunk.

**Comment by nickray** [comment]
Will be resolved by https://github.com/lpc55/lpc55-host/pull/31
